db.url=jdbc:mysql://127.0.0.1:3307/q_itoffer?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
db.username=qitoffer_app
db.password=Qitoffer@2026

